imports:
    - { resource: tables.yml }

services:
    robotea.likedislike.listener:
        class: robotea\likedislike\event\listener
        arguments:
            - @template
            - @user
            - @request
            - @auth
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
            - @robotea.likedislike.functions
        tags:
            - { name: event.listener }

    robotea.likedislike.functions:
        class: robotea\likedislike\core\likedislike
        arguments:
            - @dbal.conn
            - %robotea.likedislike.tables.likesdislikes%
            - %core.root_path%
            - %core.php_ext%
